CREATE TABLE mybatis_test
(
    id          int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(20)  DEFAULT '',
    hobbies     varchar(100) DEFAULT '',
    idols       varchar(100) DEFAULT '',
    create_time int NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
insert into mybatis_test(name, hobbies, idols, create_time)
values ('十七', '旅行', '苏轼,成龙', 1579616237),
       ('张昕宇', '侣行', '未知', 1579616237);